Update run-build.yml

diff --git a/.github/workflows/run-build.yml b/.github/workflows/run-build.yml
--- a/.github/workflows/run-build.yml
+++ b/.github/workflows/run-build.yml
@@ -26,16 +26,17 @@ jobs:
         run: npm install -g @angular/cli  
 
       - name: Build
+        id: build
         run: |
-          ERROR_OUTPUT=$(ng build 2>&1) || true
-          echo "::set-env name=BUILD_ERRORS::$ERROR_OUTPUT"
+          ERROR_OUTPUT=$(ng build --prod 2>&1) || true
+          echo "::set-output name=build_errors::$ERROR_OUTPUT"
 
       - name: Discord Webhook Action
         uses: tsickert/discord-webhook@v5.3.0
         with:
           webhook-url: ${{ secrets.DISCORD_DEVELOPMENT_ENDPOINTS_CHANNEL_WEBHOOK }}
           embed-title: "Flyingdarts.Angular"
-          embed-description: ${{ env.BUILD_ERRORS }}
+          embed-description: ${{ env.ERROR_OUTPUT }}
           embed-footer-text: ${{ github.ref_name }}
           embed-timestamp: ${{ github.event.head_commit.timestamp }}
           embed-author-name: ${{ github.event.head_commit.author }}
